### PR TITLE
Update blank.yml

### PR DESCRIPTION
**Pull request by kshitizthakur**

### CODE REVIEW

**Comment by kshitizthakur** [comment]
Nice

**Review by kshitizthakur — COMMENTED** [review]
.github/workflows/blank.yml

**Review by kshitizthakur — COMMENTED** [review]
https://github.com/yoyobantai/firstproject/pull/1#issue-496127782

**Comment by kshitizthakur** [comment]
Approved

**Review by kshitizthakur — COMMENTED** [review]
Approved

**Review by yoyobantai — APPROVED** [review]

**Comment by willox** [comment]
good work

**Comment by WardenPotato** [comment]
bruh

**Pull request merged**
